### ISSUE TITLE
Raising exception in case distinction makes value return impossible

### ISSUE THREAD

**Issue by def-** [Araq/Nim#2616] opened 2015-04-27 16:56 UTC
It would be nice if this worked, but the exception raise makes it not compile:

```nimrod
proc f(x: int): int =
  case 10
  of 0: 10
  of 1: 11
  of 2: 12
  of 3: 13
  of 4: 14
  else: raise newException(ValueError, "foo")

echo f(3)
```
```nimrod
x.nim(3, 9) Error: value of type 'int literal(10)' has to be discarded
```

**Comment by Araq** [comment] 2015-04-27 19:19
Duplicate of #842.

**Closed by Araq** 2015-04-27 19:19 UTC
Labels: Feature
