### ISSUE TITLE
C compiler error with slice

### ISSUE THREAD

**Issue by skyfex** [Araq/Nim#1963] opened 2015-01-15 06:48 UTC
The following code results in a C compiler error:

```nimrod
var intBounds: Slice[BiggestInt]
intBounds = low(int32)..high(int32) 
```

```
test.c:115:18: error: assigning to 'slice89007' (aka 'struct slice89007') from
      incompatible type 'slice89029' (aka 'struct slice89029')
        intbounds_89012 = HEX2EHEX2E_89020(((NI32) (-2147483647 -1)), ((NI32) 2147483647));
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Araq** [comment] 2015-01-18 01:19
Duplicate of #794. (Hard to fix btw.)

**Closed by Araq** 2015-01-18 01:19 UTC
Labels: Codegen
