### ISSUE TITLE
`typedesc`s can't parameterize a `proc`'s return type.

### ISSUE THREAD

**Issue by MasonMcGill** [Araq/Nim#1664] opened 2014-11-19 01:43 UTC
The manual states that "once bound, typedesc params can appear in the rest of the proc signature". However, the following fails to compile:

```nim
type Point[T] = tuple[x, y: T]
proc origin(T: typedesc): Point[T] = discard
discard origin(int)
```

Based on the error message, it seems like the return type of `origin` is inferred as `Point[None]` instead of `Point[int]`:

```
test.nim(3, 14) Info: instantiation from here
test.nim(2, 11) Error: invalid type: 'proc (typedesc[int]): Point[None]{.gcsafe, locks: 0.}'
```

**Comment by Araq** [comment] 2015-03-22 15:57
Duplicate of bug #1783.

**Closed by Araq** 2015-03-22 15:57 UTC
Labels: Medium Priority, Static[T]
