### ISSUE TITLE
Iterate items in reversed order

### ISSUE THREAD

**Issue by endragor** [Araq/Nim#2457] opened 2015-04-04 15:05 UTC
Sometimes it is useful to iterate through a sequence/array/set in reversed order. I did not find such iterators in the standard library. Is there a particular reason for that?

**Comment by dom96** [comment] 2015-04-05 11:56
An ``ritems`` would be a nice addition to the stdlib, for now you can use ``countdown`` instead.

**Comment by Araq** [comment] 2015-04-11 16:52
Do we need everything in the stdlib? Can nobody use ever use integers for indexing anymore? I'm closing this.

**Closed by Araq** 2015-04-11 16:52 UTC
Labels: Feature, Stdlib

**Comment by endragor** [comment] 2015-04-11 17:14
I cannot use integers for indexing doubly linked lists. Or trees.

**Comment by WaywardWizard** [comment] 2026-03-14 22:25
I see this is closed but i just want to say as a user i prefer the approach of nim and would not want this kind of thing in std. Nim has powerful, simple "primitives" in std and you build up with them. What you can build with primitives trivially does not need to be in std.

```
iterator reversed[T](x: openArray[T]): T =
  for ix in 0..(-1+len(x)):
    yield x[^ix]
```

Benefits of this for me are i can fit the language in my head, i know how everything works, and code is more transparent because its made up of well understood and simple primitives. The simpler and clearer your primitives the more powerful your language. 

Unpopular opinion but i believe its the correct one. Following popular opinion would reproduce popular language X, and no-one can point to X and say they did it "right".
