### ISSUE TITLE
Enhancement: Dash docset

### ISSUE THREAD

**Issue by i-c** [Araq/Nim#2628] opened 2015-05-01 16:48 UTC
[Dash](https://kapeli.com/dash) is an app for OS X and iOS that keeps locally stored, indexed copies of documentation for assorted systems, and has plugins that integrate with tons of other apps (Emacs, Sublime Text, terminal lookups, etc) to allow easy searching/lookups of any of the relevant docs.

It looks [creating a docset](https://kapeli.com/docsets#dashDocset) for it is designed to work with existing sets of HTML docs, with the main extra thing needed being an SQLite database that matches entry name, entry type (type, procedure, keyword, etc), and link to file/anchor in the HTML docs.

**Comment by reactormonk** [comment] 2015-05-01 16:53
Duplicate of https://github.com/Araq/Nim/issues/1401

**Closed by reactormonk** 2015-05-01 16:53 UTC
