### ISSUE TITLE
Error with closures and for loop

### ISSUE THREAD

**Issue by kirbyfan64** [Araq/Nim#2440] opened 2015-03-31 20:08 UTC
```nim
proc main() =
  var s: seq[string] = @[]
  proc f() = echo s

  for x in s: f()
  f()

main()
```

Output:

```
ryan@DevPC-LX:~/langtest/nim/clos2$ nim c --parallelBuild:1 clos2
/etc/nim.cfg(53, 2) Hint: added path: '/home/ryan/.babel/pkgs/' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/fcp-0.1.0' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/lua-1.0' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/argument_parser-0.2.0' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/babel-0.2.0' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/commandeer-0.3.0' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/aporia-0.2.0' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/NimBorg-0.0.2' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/cairo-1.0' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/nimble-0.6.0' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/c2nim-0.9.7' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/nake-1.3' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/gtk2-1.0' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/compiler-0.10.3' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/pas2nim-0.9.6' [Path]
/etc/nim.cfg(54, 2) Hint: added path: '/home/ryan/.nimble/pkgs/' [Path]
Hint: used config file '/etc/nim.cfg' [Conf]
Hint: used config file '/home/ryan/.config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: clos2 [Processing]
/home/ryan/stuff/Downloads/clang+llvm-3.6.0-x86_64-linux-gnu/bin/clang -c -w  -I/usr/local/lib/nim -o /home/ryan/langtest/nim/clos2/nimcache/clos2.o /home/ryan/langtest/nim/clos2/nimcache/clos2.c
/home/ryan/langtest/nim/clos2/nimcache/clos2.c:450:37: error: use of undeclared
      identifier 'HEX3Aenv_90281'; did you mean 'HEX3Aenv_90287'?
        LOC9.ClPrc = f_90025; LOC9.ClEnv = HEX3Aenv_90281;
                                           ^~~~~~~~~~~~~~
                                           HEX3Aenv_90287
/home/ryan/langtest/nim/clos2/nimcache/clos2.c:389:11: note: 'HEX3Aenv_90287'
      declared here
        TY90254* HEX3Aenv_90287;
                 ^
1 error generated.
Error: execution of an external program failed
ryan@DevPC-LX:~/langtest/nim/clos2$ 
```

If I move the first call to `f` out of the for loop or remove either of the calls, no error occurs. Adding the`{.closure.}` pragma to `f` makes no difference.

**Comment by Araq** [comment] 2015-04-24 00:45
Duplicate of some lamba lifting bug.

**Closed by Araq** 2015-04-24 00:45 UTC
Labels: Codegen
