### ISSUE TITLE
Multiple definition errors

### ISSUE THREAD

**Issue by EXetoC** [Araq/Nim#1059] opened 2014-03-31 10:38 UTC
Compiling https://github.com/nimrod-code/mongo/blob/master/tests/mongo.nim
fails with:
```
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o: In function `add_125634':
mongo_mongo.c:(.text+0xa2): multiple definition of `add_125634'
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o:mongo_mongo.c:(.text+0xa2): first defined here
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o: In function `add_125581':
mongo_mongo.c:(.text+0x167): multiple definition of `add_125581'
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o:mongo_mongo.c:(.text+0x167): first defined here
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o: In function `addbinary_125700':
mongo_mongo.c:(.text+0x213): multiple definition of `addbinary_125700'
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o:mongo_mongo.c:(.text+0x213): first defined here
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o: In function `inititer_125347':
mongo_mongo.c:(.text+0x2ce): multiple definition of `inititer_125347'
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o:mongo_mongo.c:(.text+0x2ce): first defined here
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o: In function `mongomongoInit':
mongo_mongo.c:(.text+0x352): multiple definition of `mongomongoInit'
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o:mongo_mongo.c:(.text+0x352): first defined here
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o: In function `mongomongoDatInit':
mongo_mongo.c:(.text+0x38d): multiple definition of `mongomongoDatInit'
/home/ex/src/nim-mongo/tests/nimcache/mongo_mongo.o:mongo_mongo.c:(.text+0x38d): first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/../../../../lib/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
Error: execution of an external program failed
```

**Comment by Araq** [comment] 2015-03-23 11:54
Duplicate of #2392.

**Closed by Araq** 2015-03-23 11:54 UTC
Labels: Low Priority
