### ISSUE TITLE
No overloading resolution with deprecated procs

### ISSUE THREAD

**Issue by def-** [Araq/Nim#2414] opened 2015-03-26 14:44 UTC
```nimrod
type F = object
  x: int

proc `[]`(f: F, y: int): int = f.x
proc `[]`(f: var F, y: int): var int = f.x

{.deprecated: [mget: `[]`].}

var f: F
inc f.mget(0)
```
```
min.nim(10, 6) Warning: use [] instead; mget is deprecated [Deprecated]
min.nim(10, 6) Warning: use [] instead; mget is deprecated [Deprecated]
min.nim(10, 4) Error: type mismatch: got (int)
but expected one of: 
system.inc(x: var T, y: int)
```
Should call the second `[]` instead.

**Comment by Araq** [comment] 2015-03-26 18:45
Well since there are slightly more verbose means to accomplish the same this is either low priority or even "won't fix".

**Comment by def-** [comment] 2015-03-26 19:16
How would I do that more verbosely?

**Comment by Araq** [comment] 2015-03-26 19:59
proc mget(f: var F, y: int): var int {.deprecated.} = f.x

**Comment by def-** [comment] 2015-03-26 20:01
This doesn't give the alternative to use `[]` instead unfortunately.

**Comment by StefanSalewski** [comment] 2015-03-27 16:40
I tried to report that bug months ago already, unfortunately my wording was not really good,

https://github.com/Araq/Nim/issues/1762

For me that is really an ugly bug, with it all the deprecated lists generate more harm than benefit due to the misleading error messages.

**Comment by reactormonk** [comment] 2015-03-27 18:32
Duplicate of #1762

**Closed by reactormonk** 2015-03-27 18:32 UTC
Labels: Feature, Low Priority
