### ISSUE TITLE
Universal function call syntax does not always work with generics

### ISSUE THREAD

**Issue by r-ku** [Araq/Nim#2898] opened 2015-06-10 11:36 UTC
```nim
    type
        Foo[T] = object
            a: T

    proc init[T](self: var Foo[T], n: T) =
        self.a = n

    proc init[T](_: typedesc[Foo[T]], n: T): Foo[T] =
        init[T](result, n)

    proc new[T](_: typedesc[Foo[T]], n: T): ref Foo[T] =
        new(result)
        init(result[], n)

    var f: Foo[int]
    # test.nim(66, 6) Error: type mismatch: got (Foo[system.int])
    # but expected one of: 
    # test.init(_: typedesc[Foo[init.T]], n: T)
    # test.init(self: var Foo[init.T], n: T)
    f.init[int](1)
    echo f.repr
    # but  init[int](f, 1) works
    
    # test.nim(74, 18) Error: type mismatch: got (typedesc[Foo[system.int]])
    # but expected one of: 
    # test.init(_: typedesc[Foo[init.T]], n: T)
    # test.init(self: var Foo[init.T], n: T)
    echo Foo[int].init[int](1).repr

    # test.nim(78, 19) Error: type mismatch: got (typedesc[Foo[system.int]], int literal(1))
    # but expected one of: 
    # proc (self: var Foo[system.int], n: int){.gcsafe, locks: 0.}
    echo init[int](Foo[int], 1).repr
    
    # test.nim(84, 24) Error: type mismatch: got (ref Foo[system.float], typedesc[float])
    # but expected one of: 
    # system.[](a: array[Idx, T], x: Slice[system.int])
    # system.[](a: array[Idx, T], x: Slice[[].Idx])
    # system.[](s: string, x: Slice[system.int])
    # system.[](s: seq[T], x: Slice[system.int])
    # macros.[](n: NimNode, i: int)
    echo Foo[float].new[float](1.1).repr
    # but new[float](Foo[float], 1.1) works
```
However it works without templates:
```nim
    type
        Foo = object
            a: int

    proc init(self: var Foo, n: int) =
        self.a = n

    proc init(_: typedesc[Foo], n: int): Foo =
        init(result, n)

    proc new(_: typedesc[Foo], n: int): ref Foo =
        new(result)
        init(result[], n)

    var f: Foo
    f.init(1)                # works
    echo f.repr
    echo Foo.init(2).repr    # works
    echo Foo.new(3).repr     # works
```

**Comment by Araq** [comment] 2015-06-10 13:13
duplicate of #1782.

**Closed by Araq** 2015-06-10 13:13 UTC
