### ISSUE TITLE
The inc operation failed to raise exceptions on subrange type

### ISSUE THREAD

**Issue by arthurtw** [Araq/Nim#1829] opened 2015-01-02 12:10 UTC
The `inc`, `dec`, `succ`, `pred` operations failed to raise exceptions on a subrange type. For example:
```
type
  Subrange = range[0..5]
var a: Subrange = 5

inc(a)
echo a # 6
```

**Comment by Araq** [comment] 2015-01-05 14:41
Duplicate of #1344

**Closed by Araq** 2015-01-05 14:41 UTC
