### ISSUE TITLE
file named 'test.nim' causes problem with 'test' template in unittest module

### ISSUE THREAD

**Issue by glycerine** [Araq/Nim#382] opened 2013-04-08 01:21 UTC
Closing issue #380 an opening this one instead with a better and more meaningful title.

This has to do with the name of a small test file being "test.nim". The name of a macro from the unittest module is also "test"... and appears to be some undesirable crosstalk between the name of the file and the name of the template.  This happens on both OSX and Linux (x86_64), at revision 6f1adf689459a41e3c4362a795ad3d39d010fbbc on master.

In the failure scenario, it appears as though the template test is no longer actually instatiating the 'test' template... because the variable TestStatusIMPL is nowhere to be found.

### the program (complete):

jaten@i7:~/pkg/nimrod/play$ cat test.nim
```
import unittest

template t(a: int): expr = "int"
template t(a: string): expr = "string"

test "templates can be overloaded":
   check t(10) == "int"
   check t("test") == "string"

```
jaten@i7:~/pkg/nimrod/play$ 

### when the file is named test.nim, it fails to compile:

jaten@i7:~/pkg/nimrod/play$ nimrod c test.nim
config/nimrod.cfg(36, 11) Hint: added path: '/home/jaten/.babel/libs/' [Path]
Hint: used config file '/home/jaten/pkg/nimrod/install/nimrod/config/nimrod.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
Hint: unittest [Processing]
Hint: macros [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: times [Processing]
Hint: posix [Processing]
Hint: terminal [Processing]
lib/pure/unittest.nim(140, 15) Info: instantiation from here
lib/pure/unittest.nim(102, 16) Error: undeclared identifier: 'TestStatusIMPL'

### copy the file, renaming it, and try again with the exact same contents, and it works:

jaten@i7:~/pkg/nimrod/play$ cp test.nim notNamedTest.nim
jaten@i7:~/pkg/nimrod/play$ nimrod c notNamedTest.nim
config/nimrod.cfg(36, 11) Hint: added path: '/home/jaten/.babel/libs/' [Path]
Hint: used config file '/home/jaten/pkg/nimrod/install/nimrod/config/nimrod.cfg' [Conf]
Hint: system [Processing]
Hint: notNamedTest [Processing]
Hint: unittest [Processing]
Hint: macros [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: times [Processing]
Hint: posix [Processing]
Hint: terminal [Processing]
gcc -c -w -I/home/jaten/pkg/nimrod/install/nimrod/lib -o /home/jaten/pkg/nimrod/play/nimcache/notNamedTest.o /home/jaten/pkg/nimrod/play/nimcache/notNamedTest.c
gcc -o /home/jaten/pkg/nimrod/play/notNamedTest /home/jaten/pkg/nimrod/play/nimcache/terminal.o /home/jaten/pkg/nimrod/play/nimcache/posix.o /home/jaten/pkg/nimrod/play/nimcache/times.o /home/jaten/pkg/nimrod/play/nimcache/parseutils.o /home/jaten/pkg/nimrod/play/nimcache/strutils.o /home/jaten/pkg/nimrod/play/nimcache/os.o /home/jaten/pkg/nimrod/play/nimcache/macros.o /home/jaten/pkg/nimrod/play/nimcache/unittest.o /home/jaten/pkg/nimrod/play/nimcache/system.o /home/jaten/pkg/nimrod/play/nimcache/notNamedTest.o -ldl
Hint: operation successful (15057 lines compiled; 0.188 sec total; 20.209MB) [SuccessX]
jaten@i7:~/pkg/nimrod/play$

**Comment by Araq** [comment] 2015-03-23 11:57
Duplicate of #497.

**Closed by Araq** 2015-03-23 11:57 UTC
Labels: Low Priority
