### ISSUE TITLE
Changing ':' to '=' results in compiler crash in GetUniqueType

### ISSUE THREAD

**Issue by endragor** [Araq/Nim#2456] opened 2015-04-04 13:07 UTC
I made a typo using `=` instead of `:` in var declaration. It resulted in compiler crash:
```
Error: internal error: GetUniqueType
No stack traceback available
```

The shortest way to reproduce:
```nim
var bug = int
```

**Comment by reactormonk** [comment] 2015-04-04 21:34
Duplicate of https://github.com/Araq/Nim/issues/1183 - it's fixed in devel.

**Closed by reactormonk** 2015-04-04 21:34 UTC
