### ISSUE TITLE
Allow selective destructuring in `var` and `let`

### ISSUE THREAD

**Issue by mrordinaire** [Araq/Nim#1844] opened 2015-01-03 09:44 UTC
```Nim
type
  Body = tuple[x, y, z, vx, vy, vz, mass: float64]
  NBody = array[0..4, Body]

proc energy(bodies: NBody): float64 =
  var dx, dy, dz, distance: float64

  for i in low(bodies)..high(bodies):
    let (ix, iy, iz, ivx, ivy, ivz, imass) = bodies[i]
    result += 0.5 * imass * (ivx * ivx + ivy * ivy + ivz * ivz)
    for j in i+1..high(bodies):
      let (jx, jy, jz, jvx, jvy, jvz, jmass) = bodies[j] # jvx, jvy and jvz is never used
      dx = ix - jx
      dy = iy - jy
      dz = iz - jz
      distance = sqrt(dx*dx + dy*dy + dz*dz)
      result -= (imass * jmass) / distance
```

For the above piece of code, `jvx`, `jvy` and `jvz` is never used. It would be nice to be able to say something like the following, where `_` denotes the field in that position is ignored.

```Nim
let (jx, jy, jz, _, _, _, jmass) = bodies[j]
```

Currently the compiler just reports `Error: invalid token: _ (\95)`.

**Comment by Araq** [comment] 2015-03-12 11:26
Duplicate of #2154.

**Closed by Araq** 2015-03-12 11:26 UTC
Labels: Feature
