### ISSUE TITLE
Assigning an iterator to a variable causes internal error

### ISSUE THREAD

**Issue by bluenote10** [Araq/Nim#2512] opened 2015-04-10 21:59 UTC
I was trying to assign an iterator to a variable like this:

    iterator myIter: string =
      yield "Hello"
      yield "World"
    var it = myIter   # causes: Error: internal error: proc has no result symbol
    var it = myIter() # causes: Error: undeclared identifier: 'myIter'

Is this supposed to work? [This issue](https://github.com/Araq/Nim/issues/2094) mentions the problem for `{.inline.}` iterators only, also suggesting an error message like "[inline] iterators are not first-class / cannot be assigned to variables".

The traceback in case of the internal error looks like this:

    nim.nim(94)              nim
    nim.nim(56)              handleCmdLine
    main.nim(252)            mainCommand
    main.nim(63)             commandCompileToC
    modules.nim(203)         compileProject
    modules.nim(151)         compileModule
    passes.nim(197)          processModule
    passes.nim(137)          processTopLevelStmt
    cgen.nim(1210)           myProcess
    ccgstmts.nim(1079)       genStmts
    ccgexprs.nim(2062)       expr
    ccgstmts.nim(1079)       genStmts
    ccgexprs.nim(2062)       expr
    ccgstmts.nim(1079)       genStmts
    ccgexprs.nim(2081)       expr
    ccgstmts.nim(250)        genVarStmt
    ccgstmts.nim(233)        genSingleVar
    ccgstmts.nim(86)         loadInto
    ccgexprs.nim(1968)       expr
    cgen.nim(780)            genProc
    cgen.nim(740)            genProcNoForward
    cgen.nim(656)            genProcAux
    msgs.nim(836)            internalError
    msgs.nim(813)            liMessage
    msgs.nim(715)            handleError

(0.10.3 devel branch updated an hour ago)

**Comment by Araq** [comment] 2015-04-10 22:07
Duplicate of #2094.

**Closed by Araq** 2015-04-10 22:07 UTC
