### ISSUE TITLE
The `async` pragma doesn't work with forward declared procs

### ISSUE THREAD

**Issue by l04m33** [Araq/Nim#2562] opened 2015-04-15 01:58 UTC
```nimrod
import asyncdispatch

proc callee(i: int): Future[int] {.async.}

proc caller() {.async.} =
    echo($(await callee(9)))

proc callee(i: int): Future[int] =
    await sleepAsync(1)
    return i + 1

when isMainModule:
    caller()
```

When compiled, the above program will produce an error message:

> lib/core/macros.nim(722, 5) Error: cannot add to node kind: nkEmpty

Other pragmas such as `nimcall` worked fine.

I'm using e281d41 from the devel branch.

**Comment by dom96** [comment] 2015-04-15 10:07
Duplicate of #1970

**Closed by dom96** 2015-04-15 10:07 UTC
