### ISSUE TITLE
nimsuggest errors running commands

### ISSUE THREAD

**Issue by gradha** [Araq/Nim#2341] opened 2015-03-15 08:43 UTC
I tried using the new ``nimsuggest`` command but it doesn't seem to work well:
```
$ nimsuggest --stdin nimsuggest.nim
Hint: used config file '/Users/gradha/project/nimrod/git/compiler/nimsuggest/nimsuggest.nim.cfg' [Conf]
usage: sug|con|def|use file.nim[;dirtyfile.nim]:line:col
type 'quit' to quit
type 'debug' to toggle debug mode on/off
type 'terse' to toggle terse mode on/off
> def nimsuggest.nim:49:9
Error: cannot open '/Users/gradha/lib/system.nim'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(12, 7) Error: cannot open 'strutils'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(12, 17) Error: cannot open 'os'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(12, 21) Error: cannot open 'parseopt'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(12, 31) Error: cannot open 'parseUtils'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(13, 7) Error: cannot open 'options'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(13, 16) Error: cannot open 'commands'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(13, 26) Error: cannot open 'modules'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(13, 35) Error: cannot open 'sem'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(13, 40) Error: cannot open 'passes'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(13, 48) Error: cannot open 'passaux'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(13, 57) Error: cannot open 'msgs'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(13, 63) Error: cannot open 'nimconf'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(14, 2) Error: cannot open 'extccomp'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(14, 12) Error: cannot open 'condsyms'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(14, 22) Error: cannot open 'lists'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(14, 29) Error: cannot open 'net'
project/nimrod/git/compiler/nimsuggest/nimsuggest.nim(14, 34) Error: cannot open 'rdstdin'
def	skUnknown	nimsuggest.parseQuoted.parseUntil	Error Type	/Users/gradha/project/nimrod/git/compiler/nimsuggest/nimsuggest.nim	49	""
```
For comparison, the following happens using nimrod's 0.9.6 idetools:
```
nimrod idetools --def --track:"/Users/gradha/project/nimrod/git/compiler/nimsuggest/nimsuggest.nim,49,9" "nimsuggest.nim"
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/badger_bits-0.2.5' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/dropbox_filename_sanitizer-0.4.1' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/gh_nimrod_doc_pages-0.2.4' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/linagl-0.1.1' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/number_files-0.2.2' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/nake-1.4' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/awesome_rmdir-0.2.1' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/nimble-0.6.0' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/ipsumgenera-0.1.0' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/c2nim-0.9.6' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/x-0.1.1' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/x11-1.0' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/argument_parser-0.3.1' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/lazy_rest-0.2.2' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/genieos-9.4.3' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/midnight_dynamite-1.0.0' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/gradha/.babel/pkgs/' [Path]
Hint: used config file '/Users/gradha/project/nimrod/0.9.6_zip/config/nimrod.cfg' [Conf]
def	skProc	parseutils.parseUntil	proc (string, var string, char, int): int{.inline, gcsafe.}	/Users/gradha/project/nimrod/0.9.6_zip/lib/pure/parseutils.nim	163	5	"parses a token and stores it in ``token``. Returns\x0A the number of the parsed characters or 0 in case of an error. A token\x0A consists of any character that is not the `until` character."
```
Also, why is a new command added instead of rewriting ``idetools``? Is it so hard to maintain compatibility with the previous command line interface? This change breaks tools depending on it and makes the [documentation](http://nim-lang.org/idetools.html) and [test suite](https://github.com/Araq/Nim/tree/devel/tests/caas) useless.

**Comment by StefanSalewski** [comment] 2015-03-15 14:38
Great that you tested it. I tried a few days ago and failed, thought I did something wrong. Please let me know if you have some success. I think it should work, it is used in Aporia GTK2.

**Comment by dom96** [comment] 2015-03-15 14:41
I think nimsuggest needs to be in the same directory as the nim compiler in order to find the standard library.

**Comment by StefanSalewski** [comment] 2015-03-15 16:54
Does not really help. Used same command as gradha, same errors. Nim 0.10.3 built two weeks ago. Nimble install of nimsuggest failed also, so I compiled manually. (c2nim nimble install worked.)

**Comment by gradha** [comment] 2015-03-15 17:19
Placing the binaries together works for me. I had the ``nimsuggest`` binary in ``$PATH`` but another directory (``~/bin``) since there is no instruction as to where to place it. After I moved it to the same directory where the compiler is the errors stopped and the returned info was the same as in 0.9.6.
```
$ which nim nimsuggest
/Users/gradha/project/nimrod/root/bin/nim
/Users/gradha/project/nimrod/root/bin/nimsuggest
```

**Comment by StefanSalewski** [comment] 2015-03-15 18:28
$ pwd
/home/stefan/Nim/bin
stefan@AMD64X2 ~/Nim/bin $ ls -la
total 3996
drwxr-xr-x 1 stefan stefan      72 Mar 15 17:43 .
drwxr-xr-x 1 stefan stefan     470 Mar  4 00:52 ..
-rw-r--r-- 1 stefan stefan      64 Mar  4 00:36 empty.txt
-rwxr--r-- 1 stefan stefan 2352640 Mar  4 00:42 nim
-rwxr-xr-x 1 stefan stefan 1721072 Mar 15 17:41 nimsuggest
-rw-r--r-- 1 stefan stefan    5318 Mar 15 17:43 nimsuggest.nim
stefan@AMD64X2 ~/Nim/bin $ nimsuggest --stdin nimsuggest.nim
config/nim.cfg(53, 2) Hint: added path: '/home/stefan/.babel/pkgs/' [Path]
config/nim.cfg(54, 2) Hint: added path: '/home/stefan/.nimble/pkgs/compiler-0.10.3' [Path]
config/nim.cfg(54, 2) Hint: added path: '/home/stefan/.nimble/pkgs/c2nim-0.9.7' [Path]
config/nim.cfg(54, 2) Hint: added path: '/home/stefan/.nimble/pkgs/x11-1.0' [Path]
config/nim.cfg(54, 2) Hint: added path: '/home/stefan/.nimble/pkgs/nimble-0.6.0' [Path]
config/nim.cfg(54, 2) Hint: added path: '/home/stefan/.nimble/pkgs/' [Path]
Hint: used config file '/home/stefan/Nim/config/nim.cfg' [Conf]
usage: sug|con|def|use file.nim[;dirtyfile.nim]:line:col
type 'quit' to quit
type 'debug' to toggle debug mode on/off
type 'terse' to toggle terse mode on/off
> def nimsuggest.nim:49:9
/home/stefan/.nimble/pkgs/compiler-0.10.3/compiler/docgen.nim(16, 39) Error: cannot open 'rstast'
/home/stefan/.nimble/pkgs/compiler-0.10.3/compiler/docgen.nim(16, 47) Error: cannot open 'rst'
/home/stefan/.nimble/pkgs/compiler-0.10.3/compiler/docgen.nim(16, 52) Error: cannot open 'rstgen'
/home/stefan/.nimble/pkgs/compiler-0.10.3/compiler/docgen.nim(16, 67) Error: cannot open 'highlite'

> quit

Maybe I should try to reinstall latest Nim and nimsuggest. Have you any idea about the commands? sug may give list of suggestions, but other commands?

**Comment by StefanSalewski** [comment] 2015-03-15 18:39
$ locate docgen.nim
/home/stefan/.nimble/pkgs/compiler-0.10.3/compiler/docgen.nim
/home/stefan/Nim/compiler/docgen.nim

Strange. When nimble tried to install nimsuggest, it tried to reinstall Nim compiler but failed. Can nimble install latest Nim from devel, or should I install a fresh Nim from git devel manually? And is there a prefered path where nimsuggest then may work?

**Comment by Araq** [comment] 2015-03-15 18:40
If both nim and nimsuggest are in the same dir, either both find the stdlib or both don't. they use the very same code to find the stdlib.

**Comment by StefanSalewski** [comment] 2015-03-15 19:00
For me not currently. But I installed nimsuggest a week after NIm itself. Will reinstall both soon...

**Comment by StefanSalewski** [comment] 2015-03-22 11:15
As fowl and other confirmed on IRC (http://irclogs.nim-lang.org/18-03-2015.html) nimble install at least on Linux fails. I got it to compile manually after moving nimsuggest directory two layers up in directory tree, but test commands mentioned by gradha gave many error messages.

**Comment by Gravityzwell** [comment] 2015-03-22 13:03
Also works for me (Windows) by ensuring nimsuggest.exe is in the bin folder.

**Comment by dom96** [comment] 2015-03-22 14:09
In the long run nimsuggest should be installable via Nimble.

**Comment by StefanSalewski** [comment] 2015-03-30 18:50
Latest Nim devel 0.10.3 already contains the nimsuggest directory inside compiler directory. So I compiled it there.
$ pwd
/home/stefan/Nim/compiler
$ ls nimsuggest/
nimcache  nimsuggest  nimsuggest.nim  nimsuggest.nim.cfg
cp nimsuggest/nimsuggest nstest
./nstest --stdin nimsuggest/nimsuggest.nim
def nimsuggest/nimsuggest.nim:49:9
And no error messages but useful output

**Comment by pigmej** [comment] 2015-06-11 06:57
@StefanSalewski 

nimsuggest should be in `bin` directory in your case probably `/home/stefan/Nim/bin`

**Comment by reactormonk** [comment] 2015-06-11 18:29
Duplicate of https://github.com/nim-lang/nimsuggest/issues/4

**Closed by reactormonk** 2015-06-11 18:29 UTC
Labels: Documentation, Installation
