### ISSUE TITLE
Generics + inheritance – type mismatch / dispatch issues

### ISSUE THREAD

**Issue by boydgreenfield** [Araq/Nim#2724] opened 2015-05-15 01:33 UTC
This may be me misunderstanding generics *and/or* inheritance in Nim, but I'm running into type mismatch issues when trying to combine generics and inheritance. Can this be done?

Example:
```nim
import tables
 
 
type
  TableSummaryAbstract[T] = ref object {.inheritable.}
    name: string
    table: Table[string, T]
 
  TableSummaryCount = ref object of TableSummaryAbstract[int]

  TableSummaryUniqueCount = ref object of TableSummaryAbstract[int]
    my_extra_unique_count_field: int

  TableSummaryDescriptive = ref object of TableSummaryAbstract[string]
 
 
proc initTableSummaryCount(): TableSummaryCount =
  new(result)
  result.name = "Summary count"
  result.table = initTable[string, int]()
 
 
proc initTableSummaryUniqueCount(): TableSummaryUniqueCount =
  new(result)
  result.name = "Summary count"
  result.table = initTable[string, int]()
 
 
proc initTableSummaryDescriptive(): TableSummaryDescriptive =
  new(result)
  result.name = "Summary count"
  result.table = initTable[string, string]()
 
 
proc len[T](t: TableSummaryAbstract[T]): int =
  result = t.table.len
 
 
when isMainModule:
  var t1: TableSummaryCount = initTableSummaryCount()
  doAssert len(t1) == 0
```

The above fails to compile with:
```
test.nim(41, 15) Error: type mismatch: got (TableSummaryCount)
but expected one of: 
test.len(t: TableSummaryAbstract[len.T])
```

This all works fine if TableSummaryAbstract isn't a generic of course. I imagine there's also a clean-ish way to rewrite that `len` proc for every inheriting object with templates and/or macros, but I'd prefer to avoid that route if I'm just mangling the syntax.

**Comment by dom96** [comment] 2015-05-15 19:10
This seems like a bug.

I managed to get around it by explicitly converting the type of ``t1`` to a ``TableSummaryAbstract[int]``.

```nim
when isMainModule:
  var t1: TableSummaryCount = initTableSummaryCount()
  doAssert len(TableSummaryAbstract[int](t1)) == 0
```

**Comment by boydgreenfield** [comment] 2015-05-15 19:21
@dom96 Ah ha, that does indeed work. Ok – so this is a bug then, albeit one with a really nasty syntax workaround for now. :frowning:

**Comment by Araq** [comment] 2015-05-17 09:52
Duplicate of #88.

**Closed by Araq** 2015-05-17 09:52 UTC
Labels: Generics

**Comment by boydgreenfield** [comment] 2015-05-18 19:31
@Araq Fair enough, sorry I missed that earlier issue. 

Has #88 been open so long because: 1) it's hard to properly fix; or 2) it's just otherwise been neglected? If the former, I'm probably not the right person to help, but happy to take a look if (2) and somebody can point me in the right direction.[1]


[1] With the caveat that I haven't spent any time looking at the compiler code to date.
