### ISSUE TITLE
Compiler segfaults on typedef with proc pointer type (low priority)

### ISSUE THREAD

**Issue by trustable-code** [Araq/Nim#2389] opened 2015-03-22 21:00 UTC
The compiler (devel 2015-02-33) segfaults with this code:
```nim
type  
  MyClass* = ref object
    pointerToProc: proc(myClass: MyClass)

echo("Hello World")
```
This code works:
```nim
type  
  ProcPointer = proc(myClass: MyClass)
  MyClass* = ref object
    pointerToProc: ProcPointer

echo("Hello World")
```

**Comment by def-** [comment] 2015-03-22 21:05
Looks related to https://github.com/Araq/Nim/issues/2233

**Comment by def-** [comment] 2015-03-22 21:07
Looks like https://github.com/Araq/Nim/issues/1658

**Comment by Araq** [comment] 2015-03-22 22:12
Duplicate of #1658.

**Closed by Araq** 2015-03-22 22:12 UTC
