### ISSUE TITLE
Order matters when creating a set of an enum

### ISSUE THREAD

**Issue by def-** [Araq/Nim#2548] opened 2015-04-13 17:16 UTC
```nimrod
type
  X = set[Y]
  Y = enum A, B
```
This fails to compile with `min.nim(2, 9) Error: ordinal type expected`, but this works:
```nimrod
type
  Y = enum A, B
  X = set[Y]
```

**Comment by JosephTurner** [comment] 2015-04-14 03:50
http://nim-lang.org/tut1.html#forward-declarations

**Comment by goob** [comment] 2015-04-14 08:15
I believe that within a single `type` statement, you're supposed to be able to look ahead.

I don't see it explicitly in the manual, though it alludes to it when talking about mutually recursive types, where the ability to look ahead would be necessary.

http://nim-lang.org/manual.html#type-sections

**Comment by Araq** [comment] 2015-04-15 15:47
Duplicate of #417.

**Closed by Araq** 2015-04-15 15:47 UTC
Labels: type sections
